# Generated by Django 5.0.2 on 2024-02-12 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('Description', models.CharField(default='', max_length=200)),
                ('Image', models.ImageField(upload_to='media/products/')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Vehicle.category')),
            ],
        ),
    ]
