# Generated by Django 5.0.2 on 2024-02-19 07:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('mobile', models.CharField(blank=True, default='', max_length=200)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.product')),
            ],
        ),
    ]
