# Generated by Django 5.0 on 2024-02-21 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Vehicle", "0003_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="customer",
            new_name="cust",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="product",
            new_name="pro",
        ),
    ]
