# Generated by Django 5.0 on 2024-02-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Vehicle", "0004_rename_customer_order_cust_rename_product_order_pro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="mobile",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
